1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [41]:
import numpy as np
from numpy import random


a = np.zeros((4,4))


In [42]:
a +=np.arange(4)
a

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [32]:
arr = np.arange(0,16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
arr2 = np.hsplit(arr,2)
arr2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

3. soal tambahan:

misalkan kita memiliki data array seperti berikut ini :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima ? 

jika dilihat dari data, output yang diinginkan : 2, 3, 7, 11, 13, 17, 19, 23

In [43]:
num1 = np.arange(1,26)
num2 = num1.reshape(5,5)
    
def prime_factor(n):
    prime = []
    for i in n:
        flag = 0
        if i==1:
            flag=1
        for j in range(2,i):
            if i%j == 0:
                flag = 1
                break
        if flag ==0:
            prime.append(i)
    return prime
a = prime_factor(num)
arr2=np.array(a)
arr2
                


array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [ ]:
# testing

In [8]:
from numpy.random import randint

In [17]:
b = randint(1,1000,(25))
b 

array([460, 690, 721,   3, 533, 853, 128, 765, 711, 967, 733, 988, 214,
       989, 190, 910, 861, 205, 981, 156, 500, 640,  60, 711, 831])

In [18]:
arr3 = prime_factor(b)
arr3

[3, 853, 967, 733]