# IMPORT NUMPY

In [1]:
import numpy as np

In [6]:
 #Problem 1 (Generate a 1-D array containing 5 random integers from 0 to 100)
from numpy import random
np1 = random.randint(1,101, size = 5)
np1

array([13, 95,  6, 98, 89])

In [7]:
# Problem 2 (Create a 2-D array with 3 row 5 columns random integers from 0 to 100)
np2 = random.randint(1,101, size =(3,5))
np2

array([[22, 31, 47, 23, 77],
       [77, 75, 36,  9, 55],
       [47, 59, 23, 78, 72]])

In [8]:
# Problem 3 (Generate 1-D array of 30 evenly spaced element bertween 1.5 and 5.5 inclusive)
np3 = np.linspace(1.5,5.5,30)
np3

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])